# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCondorLabs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'URLImage', '~> 2.2.3'
  pod "TTGSnackbar", '~> 1.10.3'
  pod 'SkeletonView', '~> 1.14.0'
  # Pods for TestCondorLabs

  target 'TestCondorLabsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCondorLabsUITests' do
    # Pods for testing
  end

end
